### ISSUE TITLE
this is ZS-N2N's code ，right？

### ISSUE THREAD

**Issue by Zz50861** [sadjadrz/Zero-shot-image-denoising-based-on-downsampling#2]

**Comment by sadjadrz** [comment]
It's different from ZS-N2N, but it is based on it. Please refer to https://ieeexplore.ieee.org/iel8/6287639/6514899/10654252.pdf.

**Comment by Zz50861** [comment]
> It's different from ZS-N2N, but it is based on it. Please refer to https://ieeexplore.ieee.org/iel8/6287639/6514899/10654252.pdf.

I read your paper, and while checking out your code, I noticed that you wrote several functions for calculating loss and downsampling. But it seems like the function you're using is the same as ZS-N2N. Also, I couldn't find any part about calculating the loss-guid in loss function.
Can you help me with these questions? Thanks a lot!

**Comment by sadjadrz** [comment]
[GaussianSmoothLayer.zip](https://github.com/user-attachments/files/17534700/GaussianSmoothLayer.zip)
This class act as Filter operator and similar to two other losses you can produce loss guid.
good luck.

**Comment by Zz50861** [comment]
thank you
